### ISSUE TITLE
Crash if crosspost image (all media?) is deleted

### ISSUE THREAD

**Issue by opusforlife2** [Haptic-Apps/Slide#3368]
Slide version: 6.6.1-3
Android version: LOS 17.1

Trying to open an image (probably all media) in a crosspost crashes Slide if the link in the original post has been deleted.

Logs:

```
FATAL EXCEPTION: main
Process: me.ccrama.redditslide, PID: 22827
java.lang.NullPointerException: Attempt to invoke virtual method 'com.fasterxml.jackson.databind.JsonNode com.fasterxml.jackson.databind.JsonNode.get(java.lang.String)' on a null object reference
	at me.ccrama.redditslide.SubmissionViews.PopulateSubmissionViewHolder.openGif(PopulateSubmissionViewHolder.java:474)
	at me.ccrama.redditslide.SubmissionViews.PopulateSubmissionViewHolder$1.onSingleClick(PopulateSubmissionViewHolder.java:334)
	at me.ccrama.redditslide.util.OnSingleClickListener.onClick(OnSingleClickListener.java:37)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by opusforlife2** [comment]
By the way, @TacoTheDank, I caught this and other crashes in other apps with the help of your Scoop app. Truly a genius invention.

**Comment by TacoTheDank** [comment]
@opusforlife2 Aw, thanks :) (Credit also goes to the original authors in the Scoop repo's README! Wouldn't have been possible without them :))
